### ISSUE TITLE
Not Generating Any Dusts w/ Forestry & Embers

### ISSUE THREAD

**Issue by nephatrine** [oitsjustjose/Pulver#3]
Using Pulver-1.11.x-1.0, Forestry 1.11.2-5.3.4.119, and Embers 0.216. I do not get any generated dusts though for things like Dawnstone and Bronze. Is there something else needed to trigger the generation of these dusts?

**Comment by oitsjustjose** [comment]
Yes. The dusts aren't just generated for anything (because I don't particularly see why they would need to be), they're generated under circumstances in which:

* An ore is in the ore dictionary (Example: `oreCopper`)
* An ingot is in the ore dictionary with the same postfix (Example: `ingotCopper`, where 'Copper' is the postfix)
* A dust with the post fix (Example: `dustCopper`) does **not** already exist.

In this case, there is no dawnstone or bronze ore... so they would not generate.
